version: '3'

services:
  app:
    build: .
    container_name: nestjs-app
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: nestjs-postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
